version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ae:0f:ec:7c:45:3f:06:5f:57:a6:14:db:bc:d6:8e:f4"
            - "0d:86:c8:dd:03:65:25:58:af:45:c3:2d:b1:50:be:05"
      - run:
          name: config global git vars
          command: |
            git config --global user.name cyw0ng
            git config --global user.email dev.cyw0ng@gmail.com
      - run:
          name: generate docs
          command: |
            cd docs
            npm install
            npm run build
            git clone git@github.com:cyw0ng/enigma-docsite.git upstream
            rm -rf ./upstream/*
            cp -rf docs/.vuepress/dist/* ./upstream
            cd ./upstream
            git add ./.; git commit -m "circleci--[`date`]" -s
            git push