openapi: 3.0.0
info:
  title: cve-query
  version: '1.0'
  description: Client-side cve-query rest interfaces
servers: []
paths:
  /cwe/all:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-cwe-all
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples: {}
      description: Get all CWE records from Server
  /capec/all:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-capec-all
      description: Get all CAPEC records from Server
  /cve/v1:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-cve-v1
      description: Get a CVE record from Server
  /circl/info:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-circl-info
      description: Get circl info description from Server
  /capec/count:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-capec-count
      description: Get CAPEC count from Server
  /products/vendor:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-products-vendor
      description: Get all products for a vendor
  /vendors/all:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-vendors-all
      description: Get all vendors from server
  /vendors/partial:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-vendors-partial
      description: Get a slice of vendors from server
  /capec/analyze:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-capec-analyze
      description: Get CAPEC analyze info from server
components:
  schemas: {}
security: []
